/**
 * Proportionate policy-pack generator.
 *
 * NIS2 expects an in-scope entity to have basic written policies. For a small
 * company these should be short, real, and used — not enterprise binders. This
 * module emits editable Markdown starting points for the core policies, pre-
 * filled where the scan/self-assessment gives us something concrete (the
 * incident plan carries the jurisdiction's real deadlines; the vulnerability
 * policy references the Penthera scan cadence).
 *
 * These are TEMPLATES, not legal documents. Every file says so.
 */

function header(title, ctx) {
  return [
    `# ${title}`,
    "",
    `**Organisation:** ${ctx.org}  `,
    `**Owner:** _(name a responsible person)_  `,
    `**Version:** 0.1 (draft)  `,
    `**Last reviewed:** ${ctx.date}  `,
    `**Next review:** _(set a date — at least yearly)_`,
    "",
  ].join("\n");
}

function footer() {
  return [
    "",
    "---",
    "",
    "> **Editable template — not legal advice and not a certification.** Adapt it to",
    "> how your organisation actually works, then keep it short and used. An honest",
    "> two-page policy that people follow beats a long one nobody reads.",
    "> Generated by Penthera.",
    "",
  ].join("\n");
}

/** Optional one-line note about current readiness for this measure. */
function readinessNote(ctx, measure) {
  const m = ctx.readiness?.measures?.find((x) => x.id === measure);
  if (!m) return "";
  const gaps = (m.gaps || []).filter((g) => g.type !== "unanswered").map((g) => g.question);
  const gapLine = gaps.length ? ` Gaps to close: ${gaps.join("; ")}.` : "";
  return `\n> _Current readiness for this measure (from your latest Penthera run): **${m.status}**.${gapLine}_\n`;
}

const POLICIES = [
  {
    id: "information-security", measure: "a", filename: "information-security-policy.md",
    title: "Information Security Policy",
    render: (ctx) => header("Information Security Policy", ctx) + readinessNote(ctx, "a") + `
## Purpose

This policy states how ${ctx.org} protects the confidentiality, integrity, and
availability of its information and systems, proportionate to our size and risk.

## Our commitments

- We identify our most important systems and data and the main risks to them, and review this at least yearly.
- We take appropriate, proportionate technical and organisational measures to manage those risks (see the supporting policies: access control, backup, incident response, supplier security, vulnerability management).
- Management is accountable for cyber-risk and reviews it regularly.
- Every staff member is responsible for following this policy and reporting security concerns.

## Risk approach

We keep a short risk list: for each key asset, the main threats, current measures, and any accepted gaps. It is reviewed after significant changes or incidents.

## Responsibilities

- **Management:** owns cyber-risk, approves this policy, ensures resources.
- **Security owner:** maintains the policies, runs/reviews scans, tracks remediation.
- **All staff:** follow the policies, complete awareness guidance, report issues.

## Review

Reviewed at least annually and after any significant incident or change.
` + footer(),
  },
  {
    id: "access-control", measure: "i", filename: "access-control-policy.md",
    title: "Access Control Policy",
    render: (ctx) => header("Access Control Policy", ctx) + readinessNote(ctx, "i") + `
## Purpose

Ensure people and systems have only the access they need, and that access is removed promptly when no longer needed.

## Our commitments

- **Least privilege:** access is granted based on role and business need, not convenience.
- **Joiners/movers/leavers:** access is provisioned on start, changed on role change, and revoked on the last working day (keep a simple checklist).
- **Multi-factor authentication (MFA)** is enforced for email, admin/privileged accounts, and remote access.
- **Shared accounts are avoided;** where unavoidable, credentials are stored in a password manager and rotated.
- **Access is reviewed** periodically (e.g. quarterly) to catch stale accounts.

## Asset & account inventory

We keep a simple inventory of systems, who has admin access, and what data each holds. It is updated when systems or people change.

## Responsibilities

- **Security owner:** maintains the inventory and runs access reviews.
- **Managers:** request/confirm access changes for their team.

## Review

Reviewed at least annually.
` + footer(),
  },
  {
    id: "incident-response", measure: "b", filename: "incident-response-plan.md",
    title: "Incident Response Plan",
    render: (ctx) => {
      const j = ctx.jurisdiction;
      const deadlines = (j?.incidentDeadlines || []).map(
        (d) => `- **Within ${d.within}** of ${d.of} → notify ${d.to}: ${d.content}`,
      ).join("\n") || "- _(add your jurisdiction's reporting deadlines)_";
      return header("Incident Response Plan", ctx) + readinessNote(ctx, "b") + `
## Purpose

A simple, usable plan for detecting, handling, and reporting security incidents.

## Roles & contacts (fill in)

- **Incident lead:** _(name, phone)_
- **Deputy:** _(name, phone)_
- **Comms/legal:** _(name)_
- **Competent authority / CSIRT:** ${j?.authorities?.csirt || "_(your CSIRT)_"} (supervisor: ${j?.authorities?.supervisor || "_(your supervisor)_"})

## Steps

1. **Detect & record** — anyone who spots something tells the incident lead. Log time, what was seen, systems affected.
2. **Contain** — limit the damage (isolate systems, rotate credentials, revoke access).
3. **Assess** — how significant is it? Data affected, users affected, cross-border impact?
4. **Report** — meet the regulatory deadlines below.
5. **Recover** — restore from clean backups; confirm the threat is gone.
6. **Learn** — short post-incident review; update measures and this plan.

## Regulatory reporting deadlines

${deadlines}

${j?.penalties ? `> ${j.penalties}\n` : ""}
> Penthera's incident-report helper can draft the early-warning / notification /
> final-report documents against these deadlines.

## Review

Reviewed at least annually and exercised with a simple tabletop test where possible.
` + footer();
    },
  },
  {
    id: "backup-continuity", measure: "c", filename: "backup-continuity-policy.md",
    title: "Backup & Business Continuity Policy",
    render: (ctx) => header("Backup & Business Continuity Policy", ctx) + readinessNote(ctx, "c") + `
## Purpose

Ensure we can recover important data and keep operating after data loss, ransomware, or an outage.

## Our commitments

- **Regular backups** of important data and systems (automated where possible).
- **Off-site or immutable copies** so backups survive ransomware and accidental deletion.
- **Restore testing:** we test restoring from backup at least once a year — an untested backup is not a backup.
- **Recovery targets:** we know roughly how quickly we must recover (RTO) and how much data we can afford to lose (RPO).

## What we back up (fill in)

- _(list key systems/data, where each is backed up, and how often)_

## Responsibilities

- **Security/ops owner:** runs backups, performs the annual restore test, records the result.

## Review

Reviewed at least annually.
` + footer(),
  },
  {
    id: "acceptable-use", measure: "g", filename: "acceptable-use-policy.md",
    title: "Acceptable Use & Awareness Policy",
    render: (ctx) => header("Acceptable Use & Awareness Policy", ctx) + readinessNote(ctx, "g") + `
## Purpose

Set clear, proportionate expectations for how staff use company systems, and keep basic security awareness alive.

## Our commitments

- **Strong, unique passwords** stored in a password manager; **MFA** where offered.
- **Phishing awareness:** be cautious with links/attachments; verify unexpected payment or access requests out-of-band.
- **Devices** are kept updated, locked when unattended, and encrypted.
- **Data handling:** company data stays in approved systems; no sensitive data in unapproved tools.
- **Reporting:** report anything suspicious to the security owner immediately — no blame for honest reports.

## Awareness

New joiners get a short security briefing; everyone gets occasional reminders (e.g. a phishing note each quarter).

## Review

Reviewed at least annually.
` + footer(),
  },
  {
    id: "supplier-security", measure: "d", filename: "supplier-security-policy.md",
    title: "Supplier Security Policy",
    render: (ctx) => header("Supplier Security Policy", ctx) + readinessNote(ctx, "d") + `
## Purpose

Manage the security risk from suppliers and vendors — especially those with access to our data or systems.

## Our commitments

- **Supplier inventory:** we keep a list of key suppliers and what access/data each has.
- **Assessment:** before onboarding a supplier with access to sensitive data, we check their security (questionnaire, certification such as ISO 27001/SOC 2, or Penthera's passive rating for the technical part).
- **Contracts:** where proportionate, supplier contracts include security and breach-notification clauses.
- **Review:** supplier risk is reviewed periodically and when a supplier's role changes.

## Supplier list (fill in)

| Supplier | What they access | Security check done | Notes |
|----------|------------------|---------------------|-------|
| _(name)_ | _(data/systems)_ | _(yes/no + how)_    |       |

## Review

Reviewed at least annually.
` + footer(),
  },
  {
    id: "vulnerability-management", measure: "e", filename: "vulnerability-management-policy.md",
    title: "Vulnerability Management Policy",
    render: (ctx) => header("Vulnerability Management Policy", ctx) + readinessNote(ctx, "e") + `
## Purpose

Find and fix security weaknesses before they are exploited, and handle reports responsibly.

## Our commitments

- **Regular scanning:** we run Penthera against our applications and repositories on a set cadence (e.g. before each release and monthly), and track findings to closure.
- **Dependency updates:** we keep dependencies patched (e.g. Dependabot / \`npm audit\`) and act on known-vulnerable versions.
- **Prioritisation:** we fix by real risk (severity × exposure), not raw count, and record time-to-fix.
- **Disclosure:** we provide a way to report vulnerabilities to us (a \`SECURITY.md\` / security contact) and respond promptly.
- **Verification:** fixes are confirmed by re-scanning against a baseline before they're considered closed.

## Cadence (fill in)

- Application scan: _(e.g. every release + monthly)_
- Dependency review: _(e.g. weekly automated)_
- Review of open findings: _(e.g. monthly)_

## Review

Reviewed at least annually.
` + footer(),
  },
];

/** Build the policy pack as [{ filename, content }]. */
export function buildPolicyPack(ctx = {}) {
  const context = {
    org: ctx.org || "Your organisation",
    date: ctx.date || "",
    jurisdiction: ctx.jurisdiction || null,
    readiness: ctx.readiness || null,
  };
  return POLICIES.map((p) => ({
    id: p.id,
    measure: p.measure,
    filename: p.filename,
    title: p.title,
    content: p.render(context),
  }));
}

/** Index/README for the pack. */
export function policyPackIndex(pack, ctx = {}) {
  const L = [];
  L.push(`# Policy pack — ${ctx.org || "Your organisation"}`);
  L.push("");
  L.push("Proportionate, editable starting points for the core policies NIS2 expects. **Templates, not legal advice.** Fill in the blanks, keep them short and used, and review at least yearly.");
  L.push("");
  L.push("| Policy | Art. 21(2) |");
  L.push("|--------|-----------|");
  for (const p of pack) L.push(`| [${p.title}](${p.filename}) | (${p.measure}) |`);
  L.push("");
  return L.join("\n");
}

export { POLICIES };
