/**
 * Human-readable Markdown security report.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { buildWstgCoverage, formatWstgMarkdown } from "../../lib/owasp-wstg.js";
import { formatComplianceMarkdown } from "../../lib/compliance/index.js";
import { buildActionPlan, formatActionPlanMarkdown } from "../../lib/remediation/index.js";

const SEV_ORDER = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
const SEV_TAG = {
  critical: "[CRIT]",
  high: "[HIGH]",
  medium: "[MED]",
  low: "[LOW]",
  info: "[INFO]",
};

function sortFindings(findings) {
  return [...(findings || [])].sort(
    (a, b) => (SEV_ORDER[a.severity] ?? 5) - (SEV_ORDER[b.severity] ?? 5),
  );
}

function countBySeverity(findings) {
  const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of findings || []) {
    if (counts[f.severity] != null) counts[f.severity]++;
  }
  return counts;
}

function mdEscape(s) {
  return String(s || "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/**
 * Generate Markdown report content from scan result.
 */
export function formatMarkdownReport(result, opts = {}) {
  const findings = sortFindings(result.findings);
  const counts = countBySeverity(findings);
  const version = opts.version || "0.2.0";
  const lines = [];

  lines.push(`# Penthera Security Report`);
  lines.push("");
  lines.push(`> Generated by [Penthera](https://github.com/danoszz/penthera) v${version}`);
  lines.push("");

  lines.push("## Executive summary");
  lines.push("");
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **Target** | \`${result.target || "unknown"}\` |`);
  lines.push(`| **Scan time** | ${result.timestamp?.replace("T", " ").slice(0, 19) || "—"} UTC |`);
  lines.push(`| **Duration** | ${result.duration ? `${(result.duration / 1000).toFixed(1)}s` : "—"} |`);
  lines.push(`| **Mode** | ${result.modes?.join(", ") || result.mode || "—"} |`);
  lines.push(`| **Reachable** | ${result.reachable ? "Yes" : "No"} |`);
  if (result.profile) lines.push(`| **Profile** | ${result.profile} |`);
  lines.push("");

  const total = findings.length;
  if (total === 0) {
    lines.push("**No security findings detected.**");
    lines.push("");
  } else {
    lines.push(
      `Found **${total}** issue(s): ` +
      `${counts.critical} critical · ${counts.high} high · ${counts.medium} medium · ` +
      `${counts.low} low · ${counts.info} info`,
    );
    lines.push("");

    if (counts.critical > 0 || counts.high > 0) {
      lines.push("> **Action required** — critical or high severity issues should be fixed before production deployment.");
      lines.push("");
    }
  }

  if (opts.baseline) {
    lines.push("## Baseline comparison");
    lines.push("");
    lines.push(`Compared against: \`${opts.baseline.path}\``);
    lines.push("");
    lines.push(`| Status | Count |`);
    lines.push(`|--------|-------|`);
    lines.push(`| New findings | ${opts.baseline.newCount} |`);
    lines.push(`| Resolved since baseline | ${opts.baseline.resolvedCount} |`);
    lines.push(`| Unchanged | ${opts.baseline.unchangedCount} |`);
    lines.push("");
  }

  lines.push(formatWstgMarkdown(buildWstgCoverage(result, result.profile || opts.profile || "standard")));

  if (result.compliance) {
    lines.push(formatComplianceMarkdown(result.compliance));
  }

  if (result.fingerprint) {
    lines.push("## Technology fingerprint");
    lines.push("");
    const fp = result.fingerprint;
    if (fp.framework) lines.push(`- **Framework:** ${fp.framework}`);
    if (fp.server) lines.push(`- **Server:** ${fp.server}`);
    if (fp.cdn) lines.push(`- **CDN:** ${fp.cdn}`);
    lines.push(`- **Security headers:** ${fp.security?.length ? fp.security.join(", ") : "none detected"}`);
    lines.push("");
  }

  if (result.openapi?.specUrl) {
    lines.push("## API surface");
    lines.push("");
    lines.push(`- **OpenAPI spec:** ${result.openapi.specUrl}`);
    lines.push(`- **Paths documented:** ${result.openapi.pathCount || "—"}`);
    lines.push(`- **Unprotected routes (spec):** ${result.openapi.unprotectedRoutes || "—"}`);
    lines.push("");
  }

  if (total > 0) {
    lines.push("## Findings");
    lines.push("");

    const grouped = {};
    for (const f of findings) {
      const sev = f.severity || "info";
      if (!grouped[sev]) grouped[sev] = [];
      grouped[sev].push(f);
    }

    for (const sev of ["critical", "high", "medium", "low", "info"]) {
      const group = grouped[sev];
      if (!group?.length) continue;

      lines.push(`### ${SEV_TAG[sev]} ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${group.length})`);
      lines.push("");
      lines.push("| Finding | URL | Source |");
      lines.push("|---------|-----|--------|");

      for (const f of group) {
        lines.push(`| **${mdEscape(f.title)}** | ${f.url ? `[link](${f.url})` : "—"} | ${mdEscape(f.source || "—")} |`);
      }
      lines.push("");

      for (const f of group) {
        if (!f.description) continue;
        lines.push(`**${f.title}**`);
        lines.push("");
        lines.push(f.description);
        if (f.url) lines.push(`\n- URL: ${f.url}`);
        if (f.status) lines.push(`- HTTP status: ${f.status}`);
        lines.push("");
      }
    }
  }

  const actionPlan = result.actionPlan || buildActionPlan(findings);
  if (actionPlan.length > 0) {
    lines.push(formatActionPlanMarkdown(actionPlan));
  }

  lines.push("---");
  lines.push("");
  lines.push("*Authorized security testing only. See Penthera README for ethical use guidelines.*");
  lines.push("");

  return lines.join("\n");
}

export function writeMarkdownReport(result, filePath, opts = {}) {
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, formatMarkdownReport(result, opts));
}

export function markdownPathFromJson(jsonPath) {
  return jsonPath.replace(/\.json$/i, ".md");
}
